### ISSUE TITLE
Redshift primary key shouldn't *have* to be called `id`

### ISSUE THREAD

**Issue by bradrobertson** [influitive/blueshift#6]
It seems as if we _can_ get metadata about redshift tables in order to figure out what the primary key is.

http://stackoverflow.com/questions/21273439/how-do-i-get-table-and-columns-information-from-redshift/29775745#29775745

this isn't high priority, so don't worry about it now, just logging for future considerations.

**Comment by gabrielmansour** [comment]
This was me. GitHub thinks I'm Shane for some reason.
